# Generated by Django 4.2.3 on 2023-07-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.JSONField(default=list, verbose_name={'items': {'keys': {'user': {'type': 'string'}}, 'type': 'dict'}, 'type': 'array'}),
        ),
    ]
